module.exports = {
  HZ: "漢字",
  BH: "總筆畫數",
  BS: "部首餘筆",
  SW: "說文",
  GYHZ: "匯纂",
  KX: "康熙",
  HD: "漢大",
  LF: "兩分",
  ZX: "字形描述",
  WBH: "五筆畫",
  VA: "異體字",
  VS: "字形變體",
  FL: "分類",

  MAP: " \uD83C\uDF0F ",
  IS_FAVORITE: "is_favorite",
  VARIANTS: "variants",
  COMMENT: "comment",
  INDEX: "索引",
  LANGUAGE: "語言",
  LABEL: "簡稱",

  SG: "鄭張",
  BA: "白-沙",
  GY: "廣韻",
  ZYYY: "中原音韻",
  DGY: "東干語",
  CMN: "普通話",
  HK: "香港",
  TW: "臺灣",
  KOR: "朝鮮",
  VI: "越南",
  JA_GO: "日語吳音",
  JA_KAN: "日語漢音",
  JA_OTHER: "日語其他",
  JA_: "日語",
  WB_: "五筆",

  FQ: "分區",
  COLOR: "顏色",
  ORDER: "排序",
  FIRST_FQ: "地圖集二分區",
  PROVINCE: "省",
  RECOMMEND: "推薦人",
  EDITOR: "維護人",

  COL_ALL_LANGUAGES: 1000,
  ALL_LANGUAGES: "*",

  TABLE_NAME: "mcpdict",
  TABLE_INFO: "info",
  EDITOR_COLUMNS: ["作者", "錄入人", "維護人"],
}